name: Tests Worktime calculator
run-name: ${{ github.actor }} Run yarn test
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v1
        with:
          node-version: 19

      - name: Install dependencies
        working-directory: worktime_calculator_next_js
        run: yarn

      - name: Run NextJs tests
        working-directory: worktime_calculator_next_js
        run: yarn test --watchAll=false
